version: '3.1'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: asatrya/wordpress:5.1.1
    restart: always
    networks:
      - internal
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      # - ./web/wp-content:/var/www/html/wp-content
      - vol_content_uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db

  db:
    build: ./mysql
    image: asatrya/mysql:5.6
    restart: always
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - vol_mysql_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  vol_content_uploads:
  vol_mysql_data:
