version: '3.1'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: asatrya/expressjs-web:1.0
    restart: always
    networks:
      - internal
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - vol_uploads:/app/uploads

  db:
    build: ./mysql
    image: asatrya/mysql:5.6
    restart: always
    networks:
      - internal
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - vol_mysql_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  vol_mysql_data:
  vol_uploads:
