version: '3.1'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: asatrya/wordpress:5.1.1
    restart: always
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env